---
# Configure application user account

- name: add artisan alias to bash_aliases file for app user
  lineinfile: dest=/home/"{{ laravel_app_user_username }}"/.bash_aliases line="alias artisan=\"php {{ laravel_app_root }}/artisan\"" state=present
  when: laravel_app_user_add_artisan_bash_aliases == true

- include: indatus_dispatcher_package.yml
  when: laravel_package_indatus_dispatcher_installed.stdout == "1"
