---

- name: configure laravel environment file
  template: src=env.environment.php.j2 dest='/vagrant/.env.{{ laravel_env_user.name }}.php'

- name: if environment is production symlink to laravel default name
  command: "cp /vagrant/.env.production.php /vagrant/.env.php"
  when: laravel_env_user.name == 'production'