---

- name: touching start file to prevent permissions problems
  file: path=/vagrant/bootstrap/start.php mode=755 state=touch

- name: configure laravel boostrap file
  template: src=bootstrap/start.php.j2 dest=/vagrant/bootstrap/start.php
