---

- name: determine if start file exists
  stat: path="{{ laravel_app_root }}/bootstrap/start.php"
  register: laravel_fact_start_file_exist

- name: ensure start file exists
  file: path="{{ laravel_app_root }}/bootstrap/start.php" state=touch
  when: laravel_fact_start_file_exist.stat.exists == false

- name: re-determine if start file exists
  stat: path="{{ laravel_app_root }}/bootstrap/start.php"
  register: laravel_fact_start_file_exist

- name: ensure start file has correct permissions
  file: path="{{ laravel_app_root }}/bootstrap/start.php" mode=0755 state=file
  when: laravel_fact_start_file_exist.stat.mode != 0775

- name: configure laravel boostrap file
  template: src=bootstrap/start.php.j2 dest="{{ laravel_app_root }}/bootstrap/start.php"

- name: test if indatus/dispatcher package is installed
  shell: 'grep -c -w "indatus/dispatcher" {{ laravel_app_root }}/composer.json'
  register: laravel_package_indatus_dispatcher_installed
  ignore_errors: True
  changed_when: False

- include: app-user.yml